# Site settings
title: Breizh Data Day
email: sophie.tardivel@doptim.eu
url: http://breizhdataday.github.io/
description: "Breizh Data Day, la conférence de Bretagne pour les amoureux de la donnée !"
keywords: "breizh, bretagne, intelligence artificielle, data, data science, open data"
date: "17 Septembre 2022 - Ploufragan en Côtes d'Armor"
entree: "Entrée gratuite"
meta_author: Sophie TARDIVEL
baseline: "Un événement de la French Tech Saint-Brieuc Bay"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18479a #80B3FF
  primary-rgb: "26,71,154" #"128,179,255"
  secondary:  763b8f  #FD6E8A
  secondary-dark: 95388d #A2122F

# Footer settings
footer:
  copyright: Innozh
  location: Contactez-nous
  social: Sur le web
  credits: Crédits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BreizhDay
  - title: github
    url: https://github.com/breizhdataday

# Postal address (add as many lines as necessary)
address:
  - line: INNOZH Technopole
  - line: 2 rue Jean Rostand BP 7
  - line: 22440 Ploufragan

# Credits content
credits: 'Créé avec Jekyll et le thème Freelancer.'

# Build settings
markdown: kramdown
permalink: pretty
collections:
  - workshop
  - conf
  - orga
  - sponsors
